spring:
  application:
    name: platform
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  jackson:
    #    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: true
  profiles:
    active: jdbc
  # 数据库连接池配置 #
  datasource:
#    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 30
      auto-commit: true
      idle-timeout: 3000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 3000
      driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB
      location: tmp
  sign: sac

platform:
  syslog:
    max: 20480
    port: 10224


jasypt:
  encryptor:
    password: platform

############################# loging #############################
logging:
  config: classpath:logback-spring.xml
  path: logs_platform
  level:
    root: info
  settings:

############################# mybatis #############################
mybatis:
  mapper-locations: classpath:mapper/*.xml


############################# 自定义权限 swagger #############################
oauth:
  swagger:
    author: platform
    base-package: com.bochtec.platform.controller
    description: 平台侧
    email: aa@qq.com
    version: 3.0.0
    url: https://aa.cc
    license: Apache 2.0
    license-url: https://www.apache.org/licenses/LICENSE-2.0.html
  shiro:
    tokenExpireTime: 43200000
    refreshTokenExpireTime: 200000
    shiroCacheExpireTime: 300000





